---
apiVersion: v1
kind: Namespace
metadata:
  name: test-pvc-ns
---
# The pod sometimes fails to be created as it depends on the default SA to be created
# for the new namespace, which causes the retry command to fail immediately.
# So, creating it here explicitly to avoid this.
apiVersion: v1
kind: ServiceAccount
metadata:
  name: default
  namespace: test-pvc-ns
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-pvc
  namespace: test-pvc-ns
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: test-pvc-consumer
  namespace: test-pvc-ns
spec:
  containers:
  - name: test-pvc-consumer
    image: registry:2
    volumeMounts:
    - name: my-volume
      mountPath: /data
  volumes:
  - name: my-volume
    persistentVolumeClaim:
      claimName: test-pvc
