apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://github.com/konflux-ci/build-service/config/default?ref=463f4e01eb8ab92cac71da97294072463b8ac49b

namespace: build-service

images:
  - name: quay.io/konflux-ci/build-service
    newName: quay.io/konflux-ci/build-service
    newTag: 463f4e01eb8ab92cac71da97294072463b8ac49b

patches:
  - target:
      group: monitoring.coreos.com
      version: v1
      kind: ServiceMonitor
      name: build-service-controller-manager-metrics-monitor
    path: remove-service-monitor.yaml
  - target:
      group: rbac.authorization.k8s.io
      version: v1
      kind: ClusterRole
      name: build-service-metrics-reader
    path: remove-metrics-reader-cluster-role.yaml
